name: Update repo from tarball
jobs:
  update-repo:
    runs-on: ubuntu-latest
    permissions:
      contents: write
  steps:
    - uses: r-hub/update-repo-from-url@v1
      with:
      url: https://cran.r-project.org/src/contrib/Archive/cli/cli_3.6.1.tar.gz
      ignore-top-directory: true
      token: ${{ secrets.GITHUB_TOKEN }}
